print('23')
import numpy as np
# data=np.loadtxt("E:\\Python\\PythonStudy\\scientiseData\\File\\data.csv",dtype=None, delimiter=',',skiprows=1,usecols=[1,2],)
# print(data)
# np.savetxt("train.csv",data,delimiter=',',fmt='%d',)
print(np.eye(5,6))
np.array([1,2,3,4,5,6])
np.array([1,2,3,4,5,6])
np.arange(0,6,1,dtype=int)
np.linspace(0,6,10)